Add and split Solr search information
wernerkrauss/awesome-silverstripe pull request #15
Opened 2020-10-03 22:16 UTC by Firesphere

2020-10-06 22:50 UTC, Firesphere commented
@wernerkrauss Could you please at least acknowledge the PR? ;)

2020-10-09 16:50 UTC, wernerkrauss commented
Could you please rebase on my latest changes to the list?

2020-10-09 22:29 UTC, Firesphere commented
Applied all feedback and linting fixes.

2020-10-09 22:29 UTC, Firesphere commented
p.s.

I renamed the incorrectly spelled "LICENCE" file to "LICENSE.md" ;)

2020-10-09 22:49 UTC, Firesphere commented
p.p.s.

@wernerkrauss , I would appreciate it if you tagged valid PR's with `hacktoberfest-accepted` ;)

2020-10-10 09:21 UTC, wernerkrauss commented
> I renamed the incorrectly spelled "LICENCE" file to "LICENSE.md" ;)
This is, according to (Leo)[https://dict.leo.org/englisch-deutsch/Lizenz] an American vs. British English issue. No problem with renaming, it was correct before.

>  I would appreciate it if you tagged valid PR's with hacktoberfest-accepted ;)
Of course, but I already tagged this repo "hacktoberfest", isn't this enough for your PR to be counted?

2020-10-10 20:57 UTC, Firesphere commented
> Of course, but I already tagged this repo "hacktoberfest", isn't this enough for your PR to be counted?

Sadly, no

According to Awesome:
> Place a file named license or LICENSE in the repo root with the license text.

2020-10-11 10:24 UTC, wernerkrauss requested changes

2020-10-11 10:24 UTC, wernerkrauss commented on README.md
> +  * ~[Slack Archive](https://slackarchive.silverstripe.org)~ Not active anymore due to Slack API changes
Although it's very informative that the archive doesn't exist anymore, awesome guidelines don't allow dead links. ATM I get a 520 error on cloudflare when I try to access the slack archive

2020-10-11 10:24 UTC, wernerkrauss commented on README.md
> +    - [Fine grained member permissions](https://github.com/Firesphere/silverstripe-solr-member-permissions) - Adds per-member based permission instead of Group based permissions.
Group should be lowercase, like member in a normal sentence

2020-10-11 10:24 UTC, wernerkrauss commented on README.md
> +    - [Fluent](https://github.com/Firesphere/silverstripe-fluent-solr) - Adds support for Fluent.
Why is "Fluent" written uppercase?

2020-10-11 10:24 UTC, wernerkrauss commented on README.md
> +  - Documentation
I wonder if we need the whole documentation and submodules. Are they awesome enough for this list? Or should they be linked from the module? 

I mean, we assume an awesome item to have proper documentation, regarding to the "awesome list specs". 

Instead you could write: 
> Full fledged search interface for Solr search, supporting up to the latest Solr version. With submodules for e.g. subsites, fluent and fulltext search compatibility.

2020-10-11 10:24 UTC, wernerkrauss commented on README.md
> +#### Solr 4
Did you update the Content section? See (updated) [CONTRIBUTING.md](https://github.com/wernerkrauss/awesome-silverstripe/blob/main/CONTRIBUTING.md)

> npx doctoc --no-title --maxlevel 3 README.md

2020-10-11 10:25 UTC, Firesphere commented on README.md
> +  * ~[Slack Archive](https://slackarchive.silverstripe.org)~ Not active anymore due to Slack API changes
That is fixed in the rebase

2020-10-11 10:25 UTC, Firesphere commented on README.md
> +    - [Fine grained member permissions](https://github.com/Firesphere/silverstripe-solr-member-permissions) - Adds per-member based permission instead of Group based permissions.
In theory, true. In practice, it refers to a class and in that regards `Member` should actually be upper case.

It's debatable, but I'm happy to make it all lower case :)

2020-10-11 10:26 UTC, Firesphere commented on README.md
> +    - [Fluent](https://github.com/Firesphere/silverstripe-fluent-solr) - Adds support for Fluent.
Because it's an external repository. It's like a name, but happy to lower case it.

2020-10-11 10:27 UTC, Firesphere commented on README.md
> +  - Documentation
Fair call, I'm not sure either way. I would personally at least leave the documentation in, but remove the submodules?

2020-10-11 10:27 UTC, Firesphere commented on README.md
> +#### Solr 4
Yes, it uses the git hook, so if it's not, that's odd. I can easily re-do it manually :)

2020-10-11 10:44 UTC, Firesphere commented on README.md
> +    - [Fine grained member permissions](https://github.com/Firesphere/silverstripe-solr-member-permissions) - Adds per-member based permission instead of Group based permissions.
I'm just gonna take all the sub points out. I think that's the better way to go :)

2020-10-11 10:45 UTC, wernerkrauss commented on README.md
> +#### Solr 4
my bad, I guess it's one level too deep and should not be part of the TOC. Sorry. for this.

2020-10-11 11:07 UTC, Firesphere commented on README.md
> +#### Solr 4
No worries :)

2020-10-11 12:03 UTC, merged

2020-10-11 12:05 UTC, wernerkrauss commented
Thanks for contributing and fixing the filename issue